version: "3.7"
name: gen_#_team_#_services
services:
  
  gen_#_team_#_api:
    build: .
    image: gen_#_team_#_api_image
    container_name: gen_#_team_#_api_container
    ports:
      - "800#:800#"
    depends_on:
      - gen_#_team_#_postgres_app
    env_file:
      - .env
    networks:
      - gen_#_team_#_api
      - gen_#_team_#_postgres_app


  gen_#_team_#_postgres_app:
    image: postgres
    container_name: gen_#_team_#_postgres_container
    ports: 
      - "543#:5432"
    env_file:
      - .env.db.docker
    volumes:
      - gen_#_team_#_postgres_volume:/var/lib/postgresql/data
    networks:
      - gen_#_team_#_postgres_app

networks:
  gen_#_team_#_postgres_app:
    name: gen_#_team_#_postgres_app
  gen_#_team_#_api:
    name: gen_#_team_#_api

volumes:
  gen_#_team_#_postgres_volume:
    name: 'gen_#_team_#_postgres_volume'